Repository KUIT-MAPU/MAPU-Frontend, pull requests merged in 2024-08, with the labels that each got.

#77 merge/feat: 72- explore page
  package-lock.json
  package.json
  src/App.tsx
  src/components/explore/ErrorPage.module.scss
  src/components/explore/ErrorPage.tsx
  src/components/explore/MapList.module.scss
  src/components/explore/MapList.tsx
  src/components/explore/SearchBar.module.scss
  src/components/timeLine/editorList/EditorList.module.scss
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/components/timeLine/keywordList/KeywordList.tsx
  src/components/timeLine/leftBar/LeftBar.module.scss
  src/components/timeLine/leftBar/LeftBar.tsx
  src/components/timeLine/mapList/MapCard.module.scss
  src/components/timeLine/mapList/MapCard.tsx
  src/components/timeLine/mapList/MapModel.tsx
  src/pages/Explore/Explore.module.scss
  src/pages/Explore/Explore.tsx
  src/pages/TimeLine/TimeLine.module.scss
  src/pages/TimeLine/TimeLine.tsx
  src/stores/keywordStore.ts
  src/types/MapType.ts
Labels: feat

#79 fix: syntax error
  src/components/timeLine/mapList/MapCard.tsx
  src/pages/TimeLine/TimeLine.tsx
Labels: fix

#82 feat: 탐색 페이지 키워드 선택 및 지도 키워드 렌더링
  src/components/explore/MapKeywordCard.module.scss
  src/components/explore/MapKeywordCard.tsx
  src/components/explore/MapList.module.scss
  src/components/explore/MapList.tsx
  src/components/timeLine/keywordList/KeywordList.tsx
  src/components/timeLine/mapList/MapModel.tsx
  src/pages/Explore/Explore.tsx
  src/types/MapKeywordType.tsx
  src/types/MapType.ts
Labels: feat

#85 Feat/83 follow modal
  src/assets/btn_followmodal_close.svg
  src/assets/ico_user_follower.svg
  src/assets/ico_user_following.svg
  src/components/userProfile/UserInfoBar.tsx
  src/components/userProfile/followModal/Follower.module.scss
  src/components/userProfile/followModal/Follower.tsx
  src/components/userProfile/followModal/Following.module.scss
  src/components/userProfile/followModal/Following.tsx
Labels: feat

#87 feat(ObjectPropertyBox): 객체 정보 속성 객체 연결, 태그 부분 구현
  src/App.module.scss
  src/assets/btn_delete.svg
  src/assets/btn_menu_gray.svg
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapBasicInfoContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapBasicInfoContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapLocationInfoContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapLocationInfoContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapProducerContainer/MapProducerContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapProducerContainer/MapProducerContainer.tsx
  src/components/map/MapInfoPanel/MapContentTitleContainer.tsx
  src/components/map/MapInfoPanel/MapInfoPanel.tsx
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectList.module.scss
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectList.tsx
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectOutlineBtn.module.scss
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectOutlineBtn.tsx
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/EditorObjectInfoInputContainer.module.scss
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/EditorObjectInfoInputContainer.tsx
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/ObjectBasicInfoContainer.module.scss
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/ObjectBasicInfoContainer.tsx
  src/components/map/ObjectInfoPanel/ObjectInfoPanel.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/AddPropertyPopUp.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyContainer.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyContainer.tsx
  src/components/map/ObjectInfoPanel/PublishLinkContainer/PublishLinkContainer.module.scss
  src/components/map/ObjectInfoPanel/PublishLinkContainer/PublishLinkContainer.tsx
  src/pages/Map/Map.tsx
  src/stores/mapInfoStore.ts
  src/types/enum/MapMode.ts
  src/types/enum/ObjectPropertyType.ts
  src/types/map/object/ObjectInfo.ts
  src/types/map/object/ObjectOutline.ts
  src/types/map/object/StarRating.ts
Labels: feat, refactor, chore

#88 merge/Feat:84 base map render
  global.d.ts
  package-lock.json
  package.json
  public/index.html
  src/assets/map/ico_color_black.svg
  src/assets/map/ico_color_blue.svg
  src/assets/map/ico_color_green.svg
  src/assets/map/ico_color_purple.svg
  src/assets/map/ico_color_red.svg
  src/assets/map/ico_color_yellow.svg
  src/assets/map/ico_dot.svg
  src/assets/map/ico_dot_thick.svg
  src/assets/map/ico_dot_thin.svg
  src/assets/map/ico_expansion.svg
  src/assets/map/ico_face.svg
  src/assets/map/ico_face_thick.svg
  src/assets/map/ico_face_thin.svg
  src/assets/map/ico_face_transparent_15.svg
  src/assets/map/ico_face_transparent_30.svg
  src/assets/map/ico_line_thick.svg
  src/assets/map/ico_line_thin.svg
  src/assets/map/ico_reduction.svg
  src/assets/map/ico_share.svg
  src/assets/map/ico_share_active.svg
  src/assets/map/ico_share_inactive.svg
  src/components/global/GlobalNavigationBar.module.scss
  src/components/map/BaseMap/BaseMap.module.scss
  src/components/map/BaseMap/BaseMap.tsx
  src/components/map/BaseMap/EditDesignPanel.module.scss
  src/components/map/BaseMap/EditDesignPanel.tsx
  src/components/map/MapInfoPanel/MapInfoPanel.module.scss
  src/components/map/ObjectInfoPanel/ObjectInfoPanel.module.scss
  src/hooks/useKakaoLoader.tsx
  src/pages/Map/Map.tsx
  tsconfig.json
Labels: feat

#89 merghe/fix(map): 툴바 노란색 선택 여부 수정
  src/components/map/BaseMap/EditDesignPanel.tsx
Labels: fix

#90 mearg/feat. 객체 추가 완료 후 툴 선택 초기화하기
  src/components/map/BaseMap/BaseMap.tsx
  src/components/map/BaseMap/EditDesignPanel.tsx
Labels: feat

#94 feat:UserPage->LoginModal implemented
  src/components/global/GlobalNavigationBar.tsx
  src/components/userProfile/UserInfoBar.module.scss
  src/components/userProfile/UserInfoBar.tsx
Labels: feat

#96 feat:GlobalNavigationBar Login Modal implemented
  global.d.ts
  public/index.html
  src/components/global/GlobalNavigationBar.module.scss
  src/components/global/GlobalNavigationBar.tsx
  src/components/map/BaseMap/BaseMap.module.scss
  src/components/map/BaseMap/BaseMap.tsx
  src/components/map/BaseMap/EditDesignPanel.module.scss
  src/components/map/BaseMap/EditDesignPanel.tsx
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/UserInfoBar.module.scss
  src/components/userProfile/UserInfoBar.tsx
  src/components/userProfile/followModal/Following.module.scss
  src/components/userProfile/getNewMap/NewMap.module.scss
  src/components/userProfile/getNewMap/NewMap.tsx
  src/hooks/useKakaoLoader.tsx
  tsconfig.json
Labels: feat

#98 Feat/97 global navigation bar icon on/off
  src/assets/btn_explore_off.svg
  src/assets/btn_explore_on.svg
  src/assets/btn_home_off.svg
  src/assets/btn_home_on.svg
  src/components/global/GlobalNavigationBar.module.scss
  src/components/global/GlobalNavigationBar.tsx
  src/components/userProfile/followModal/Following.module.scss
Labels: feat

#100 merge/Feat:84 base map render
  public/index.html
  src/assets/map/ico_dot_thick_custom.svg
  src/assets/map/ico_dot_thin_custom.svg
  src/components/map/BaseMap/BaseMap.tsx
  src/components/map/BaseMap/EditDesignPanel.tsx
  src/pages/Map/Map.tsx
Labels: feat

#102 Feat/99 gallery view pagenation
  src/assets/btn_map_create.svg
  src/assets/ico_miniuser_profile.svg
  src/components/userProfile/EmptyUser.module.scss
  src/components/userProfile/EmptyUser.tsx
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: fix, feat

#104 feat: ListView implemented
  src/assets/ico_exampleuser_profile.svg
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
Labels: feat

#105 merge/feat: thin-dot 수정 및 공유 버튼 활성/비활성
  src/assets/map/ico_dot_thin_custom.svg
  src/components/map/BaseMap/BaseMap.tsx
  src/components/map/BaseMap/EditDesignPanel.tsx
  src/pages/Map/Map.tsx
Labels: feat

#108 Merge/feat: 탐색페이지 키워드 선택
  src/components/timeLine/keywordList/KeywordList.tsx
  src/pages/Explore/Explore.tsx
  src/stores/keywordStore.ts
Labels: fix

#109 feat: axios instance 생성 및 로그인/회원가입 api 연동
  src/Router.tsx
  src/apis/auth/socialLogin.ts
  src/apis/auth/useSignUpMutation.ts
  src/apis/instance.ts
  src/components/login/LoginModal.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapProducerContainer/MapProducerContainer.tsx
  src/components/profile_setting/ProfileInfoSetting.module.scss
  src/components/profile_setting/ProfileInfoSetting.tsx
  src/components/profile_setting/UserDataInputContainer.module.scss
  src/components/profile_setting/UserDataInputContainer.tsx
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/pages/Explore/Explore.tsx
  src/pages/Login/Login.tsx
  src/pages/Map/Map.tsx
  src/pages/TimeLine/TimeLine.tsx
  src/pages/login/Login.tsx
  src/stores/registerStore.ts
  src/types/BaseResponse.ts
  src/types/auth/login.ts
  src/types/enum/ResponseCode.ts
Labels: feat, refactor

#112 fix: 전역 상태 관리 메서드명 수정
  src/components/global/GlobalNavigationBar.tsx
  src/components/userProfile/UserInfoBar.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: fix

#113 Feat/107 new map cur location
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/getNewMap/NewMap.module.scss
  src/components/userProfile/getNewMap/NewMap.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: feat

#115 merge/feat: 지도 객체 delete 키로 삭제하기
  src/assets/map/ico_dot_thin_custom.svg
  src/components/map/BaseMap/BaseMap.tsx
Labels: feat

#116 Feat/114 user page styling
  src/components/global/GlobalNavigationBar.module.scss
  src/components/global/GlobalNavigationBar.tsx
  src/components/userProfile/EmptyUser.module.scss
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/UserInfoBar.module.scss
Labels: feat, style

#119 feat: 회원가입 api
  .gitignore
  package.json
  src/apis/auth/socialLogin.ts
  src/apis/auth/useSignUpMutation.ts
  src/apis/instance.ts
  src/components/profile_setting/ProfileInfoSetting.tsx
Labels: feat

#120 feat: 우측 객체 정보 뷰 패널 일부 구현
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.tsx
Labels: feat

#123 feat: 추천에디터 api 연동
  .gitignore
  src/apis/editors/fetchEditorsData.ts
  src/apis/editors/getEditorsData.ts
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/editorList/EditorModel.tsx
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/components/timeLine/headerNavigation/HeaderNavigation.module.scss
  src/components/timeLine/headerNavigation/HeaderNavigation.tsx
  src/components/timeLine/mapCard/MapCard.module.scss
  src/components/timeLine/mapCard/MapCard.tsx
  src/pages/Explore/Explore.module.scss
  src/pages/Explore/Explore.tsx
  src/pages/Map/Map.tsx
  src/pages/TimeLine/TimeLine.module.scss
  src/pages/TimeLine/TimeLine.tsx
  src/types/getEditors/EditorType.ts
Labels: feat

#125 feat:User API 팔로워,팔로잉 연동
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/UserInfoBar.tsx
Labels: feat

#128 feat/126-UserProfile-Login/out+API implented
  package.json
  src/components/userProfile/userInfoBarCard/EmptyUSerInfobar.module.scss
  src/components/userProfile/userInfoBarCard/EmptyUserInfoBar.tsx
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.module.scss
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
  src/pages/UserProfile/UserProfile.tsx
  src/stores/registerStore.ts
Labels: feat, refactor

#130 Feat/129 get user image from data
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
Labels: feat

#132 Feat/131 user profile map-data api
  public/index.html
  src/apis/editors/fetchEditorsData.ts
  src/apis/editors/getEditorsData.ts
  src/components/explore/MapList.tsx
  src/components/global/GlobalNavigationBar.module.scss
  src/components/global/GlobalNavigationBar.tsx
  src/components/map/BaseMap/BaseMap.tsx
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/components/timeLine/mapCard/MapCard.module.scss
  src/components/userProfile/EmptyUser.tsx
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/getNewMap/NewMap.module.scss
  src/components/userProfile/getNewMap/NewMap.tsx
  src/components/userProfile/userInfoBarCard/EmptyUSerInfobar.module.scss
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
  src/pages/Explore/Explore.tsx
  src/pages/Map/Map.tsx
  src/pages/TimeLine/TimeLine.module.scss
  src/pages/TimeLine/TimeLine.tsx
  src/stores/keywordStore.ts
  src/stores/registerStore.ts
  src/types/getEditors/EditorType.ts
Labels: feat

#134 Merge/feat 탐색페이지 api 연동
  package-lock.json
  package.json
  src/apis/editors/getEditorsData.tsx
  src/apis/editors/useGetEditorsData.tsx
  src/apis/follow/getFollowing.tsx
  src/apis/follow/postFollow.tsx
  src/apis/follow/useGetFollowing.tsx
  src/apis/follow/usePostFollow.tsx
  src/apis/keywords/fetchGetKeywords.tsx
  src/apis/keywords/getKeywordMap.tsx
  src/apis/keywords/getKeywords.tsx
  src/apis/keywords/keywordMap.tsx
  src/apis/mapData/exploreMap.tsx
  src/apis/mapData/followingMap.tsx
  src/apis/mapData/getExploreMap.tsx
  src/apis/mapData/getFollowingMap.tsx
  src/components/explore/MapList.module.scss
  src/components/explore/MapList.tsx
  src/components/explore/SearchPopUp.tsx
  src/components/timeLine/Dimmed.module.scss
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/editorList/EditorProfileCard.module.scss
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/components/timeLine/keywordList/KeywordList.tsx
  src/components/timeLine/leftBar/LeftBar.tsx
  src/components/timeLine/mapCard/MapCard.module.scss
  src/components/timeLine/mapCard/MapCard.tsx
  src/pages/Explore/Explore.module.scss
  src/pages/Explore/Explore.tsx
  src/pages/TimeLine/TimeLine.module.scss
  src/pages/TimeLine/TimeLine.tsx
  src/stores/keywordStore.ts
  src/types/BaseResponse.ts
  src/types/editors/EditorType.ts
  src/types/follow/FollowType.ts
  src/types/follow/FollowingType.ts
  src/types/follow/UserType.ts
  src/types/keywords/APIKeywordMapType.ts
  src/types/keywords/APIKeywordType.ts
  src/types/keywords/KeywordMapType.ts
  src/types/keywords/KeywordType.ts
  src/types/keywords/MapType.ts
  src/types/keywords/MapsType.ts
  src/types/mapData/APIExploreMapType .ts
  src/types/mapData/ExploreMapType.ts
  src/types/mapData/FollowingMapType.ts
  src/types/mapData/MapsType.ts
  src/types/mapData/UserType.ts
Labels: feat

#136 Feat/133 user follow
  src/components/userProfile/followModal/Follower.module.scss
  src/components/userProfile/followModal/Follower.tsx
  src/components/userProfile/followModal/Following.module.scss
  src/components/userProfile/followModal/Following.tsx
  src/components/userProfile/userInfoBarCard/EmptyUserInfoBar.tsx
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: feat

#138 Feat/137 user profile search
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/followModal/Follower.module.scss
  src/components/userProfile/followModal/Follower.tsx
  src/components/userProfile/followModal/Following.module.scss
  src/components/userProfile/followModal/Following.tsx
Labels: feat

#143 feat: UserPage 완
  src/assets/ico_font_alert.svg
  src/assets/ico_profile_edit.svg
  src/components/global/GlobalNavigationBar.module.scss
  src/components/userProfile/getProfileEdit/ProfileEdit.module.scss
  src/components/userProfile/getProfileEdit/ProfileEdit.tsx
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
Labels: feat

#127 feat: 글로벌 내비게이션 바 하단 로그아웃 버튼과 logout api 연동
  src/apis/auth/useLogOutMutation.ts
  src/apis/auth/useSignUpMutation.ts
  src/assets/btn_login.svg
  src/assets/btn_logout.svg
  src/assets/logout.svg
  src/components/global/GlobalNavigationBar.module.scss
  src/components/global/GlobalNavigationBar.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapLocationInfoContainer.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyContainer.tsx
  src/components/profile_setting/ProfileInfoSetting.tsx
  src/components/profile_setting/input/IdInput.tsx
  src/pages/Login/Login.tsx
  src/pages/Map/Map.module.scss
  src/pages/Map/Map.tsx
  src/stores/registerStore.ts
  src/types/enum/ResponseCode.ts
Labels: feat

#145 Fix/142 unfollow api
  src/apis/follow/getFollowing.tsx
  src/apis/follow/useGetFollowing.tsx
  src/apis/mapData/followingMap.tsx
  src/components/explore/MapKeywordCard.tsx
  src/components/explore/MapList.tsx
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/components/timeLine/mapCard/MapCard.tsx
  src/pages/Map/Map.tsx
  src/types/mapData/MapsType.ts
  src/types/mapData/UserType.ts
Labels: feat

#147 fix. UserType 경로 변경
  src/components/explore/MapList.module.scss
  src/components/explore/MapList.tsx
  src/types/UserType.ts
  src/types/follow/FollowingType.ts
  src/types/follow/UserType.ts
  src/types/mapData/APIExploreMapType .ts
  src/types/mapData/ExploreMapType.ts
Labels: feat

#148 fix. 미로그인일 때 팔로우 로직 변경
  src/components/timeLine/editorList/EditorProfileCard.tsx
Labels: feat

#150 Feat/146 user nick name page name
  src/apis/auth/useProfileEditMutation.ts
  src/components/profile_setting/ProfileInfoSetting.tsx
  src/components/profile_setting/ProfileSettingModal.tsx
  src/components/userProfile/GetUser.tsx
  src/components/userProfile/followModal/Follower.tsx
  src/components/userProfile/followModal/Following.tsx
  src/components/userProfile/getProfileEdit/ProfileEdit.tsx
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.module.scss
  src/components/userProfile/userInfoBarCard/GetUserInfoBar.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: fix, feat

#153 feat&refactor: 지도 기본 정보 조회 api 연동 및 관련 분기 처리
  src/Router.tsx
  src/apis/Map/fetchMapBasicInfo.ts
  src/components/explore/MapList.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapBasicInfoContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapBasicInfoContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapLocationInfoContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapLocationInfoContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.module.scss
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapTitleAndDescriptionInputContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapProducerContainer/MapProducerContainer.tsx
  src/components/map/MapInfoPanel/MapInfoPanel.tsx
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectList.tsx
  src/components/map/ObjectInfoPanel/ObjectInfoPanel.tsx
  src/components/map/ObjectInfoPanel/PublishLinkContainer/PublishLinkContainer.tsx
  src/components/timeLine/mapCard/MapCard.tsx
  src/pages/Map/Map.tsx
  src/stores/mapInfoStore.ts
  src/types/UserType.ts
  src/types/follow/FollowingType.ts
  src/types/map/MapBasicInfo.ts
  src/types/map/MapInfo.ts
  src/types/mapData/APIExploreMapType .ts
  src/types/mapData/ExploreMapType.ts
  src/types/mapData/FollowingMapType.ts
Labels: feat, refactor

#156 feat: 지도 페이지 api 연동, 지도 정보 수정 및 객체 선택 여부에 따른 활성화/비활성화 여부 구현 등
  src/apis/Map/useMapBookmarkEditMutation.ts
  src/apis/Map/useMapDescriptionEditMutation.ts
  src/apis/Map/useMapPublishMutation.ts
  src/apis/Map/useMapTitleEditMutation.ts
  src/assets/btn_plus_gray.svg
  src/components/explore/MapList.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapBasicInfoContainer/MapBasicInfoContainer.tsx
  src/components/map/MapInfoPanel/MapBasicInfo/MapProducerContainer/MapProducerContainer.tsx
  src/components/map/MapInfoPanel/MapInfoPanel.tsx
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectList.tsx
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectOutlineBtn.module.scss
  src/components/map/MapInfoPanel/ObjectOutlineList/ObjectOutlineBtn.tsx
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/ObjectBasicInfoContainer.module.scss
  src/components/map/ObjectInfoPanel/ObjectBasicInfo/ObjectBasicInfoContainer.tsx
  src/components/map/ObjectInfoPanel/ObjectInfoPanel.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/AddPropertyPopUp.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/AddPropertyPopUp.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyBox.tsx
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyContainer.module.scss
  src/components/map/ObjectInfoPanel/OjbectPropertyContainer/ObjectPropertyContainer.tsx
  src/components/map/ObjectInfoPanel/PublishLinkContainer/PublishLinkContainer.tsx
  src/pages/Map/Map.tsx
  src/stores/registerStore.ts
  src/types/UserType.ts
Labels: feat
