Repository KUIT-MAPU/MAPU-Frontend, pull requests merged in 2024-07, with the labels that each got.

#6 build: 상태 관리 및 서버 통신 라이브러리 설치
  package-lock.json
  package.json
  src/Router.tsx
  src/components/editor/README.md
  src/components/fileManager/README.md
  src/components/login/README.md
  src/components/map/README.md
  src/components/userProfile/README.md
  src/components/viewer/README.md
  src/pages/Editor.tsx
  src/pages/FileManager.tsx
  src/pages/Map.tsx
  src/pages/UserProfile.tsx
  src/pages/Viewer.tsx
Labels: build, chore

#8 chore: 파일 구조 및 파일명, 라우터 수정
  src/Router.tsx
  src/apis/README.md
  src/components/community/README.md
  src/components/explore/README.md
  src/components/login/README.md
  src/components/map/README.md
  src/components/myMaps/README.md
  src/components/timeLine/README.md
  src/pages/Community.tsx
  src/pages/Explore.tsx
  src/pages/MyMaps.tsx
  src/pages/Welcome.tsx
  src/stores/README.md
  src/types/README.md
Labels: chore

#12 build : 10 build deploy vercel
  .github/workflows/main.yml
  build.sh
Labels: build

#15 chore: add src/types & public/data
  public/data/README.md
  src/types/README.md
Labels: chore

#18 feat : add HeaderNavigation component
  public/MAPUimg/back_btn_active.png
  public/MAPUimg/back_btn_inactive.png
  public/MAPUimg/forward_btn_active.png
  public/MAPUimg/forward_btn_inactive.png
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/headerNavigatin/HeaderNavigation.scss
  src/components/timeLine/headerNavigatin/HeaderNavigation.tsx
  src/pages/TimeLine.tsx
Labels: feat

#20 feat: set landing page title and favicon
  public/favicon.png
  public/index.html
Labels: feat

#22 feat: 페이지별 title 정보 및 user, map path 수정
  src/Router.tsx
  src/pages/Explore.tsx
  src/pages/Map.tsx
  src/pages/TimeLine.tsx
  src/pages/UserProfile.tsx
  src/pages/Welcome.tsx
Labels: feat

#28 feat(Welcome): 랜딩 페이지 구현
  .github/pull_request_template.md
  src/App.module.scss
  src/Router.tsx
  src/assets/README.md
  src/assets/fonts/Freesentation-Bold.woff
  src/assets/fonts/Freesentation-Regular.woff
  src/assets/fonts/Freesentation-SemiBold.woff
  src/assets/mapu-logo.svg
  src/assets/welcome-banner.webp
  src/components/login/LoginModal.tsx
  src/components/login/README.md
  src/components/userProfile/GlobalNavigationBar.module.scss
  src/components/userProfile/GlobalNavigationBar.tsx
  src/pages/Welcome.tsx
  src/pages/Welcome/Welcome.module.scss
  src/pages/Welcome/Welcome.tsx
Labels: feat

#37 feat(KakaoLogin): 카카오 로그인 구현
  .gitignore
  src/Router.tsx
  src/components/login/LoginModal.tsx
  src/pages/Map.tsx
  src/pages/login/KakaoLogin.tsx
Labels: feat

#42 refactor(AuthContainer): 로그인, 프로필세팅 모달 감싸는 상위 컴포넌트 생성
  src/components/login/AuthContainer.tsx
  src/components/login/ProfileSettingModal.module.scss
  src/components/login/ProfileSettingModal.tsx
  src/pages/Welcome/Welcome.tsx
  src/stores/README.md
  src/stores/registerStore.ts
  src/types/README.md
Labels: feat, refactor

#47 feat/refactor: 프로필 세팅 모달 스타일링 및 분기 처리, ProfileInfoSetting 컴포넌트 분리
  src/assets/close.svg
  src/assets/profile_setting.svg
  src/components/login/AuthContainer.tsx
  src/components/login/LoginModal.tsx
  src/components/login/ProfileInfoSetting.module.scss
  src/components/login/ProfileInfoSetting.tsx
  src/components/login/ProfileSettingModal.module.scss
  src/components/login/ProfileSettingModal.tsx
  src/components/timeLine/editorList/EditorList.module.scss
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/pages/login/Login.tsx
Labels: feat, refactor

#52 feat: 추천키워드 전역관리
  src/App.tsx
  src/components/timeLine/editorList/EditorList.tsx
  src/components/timeLine/editorList/EditorProfileCard.module.scss
  src/components/timeLine/keywordList/KeywordList.tsx
  src/components/timeLine/leftBar/LeftBar.tsx
  src/components/timeLine/mapList/MapCard.tsx
  src/components/timeLine/mapList/MapList.tsx
  src/pages/Explore/Explore.tsx
  src/pages/TimeLine/TimeLine.tsx
  src/stores/keywordStore.ts
Labels: feat

#54 feat(TimeLine): 홈(타임라인)에서 딤드 처리 및 로그인 모달 표시하기 (전역 상태 추가)
  src/components/login/LoginModal.tsx
  src/components/profile_setting/ProfileInfoSetting.tsx
  src/components/timeLine/editorList/EditorProfileCard.module.scss
  src/components/timeLine/editorList/EditorProfileCard.tsx
  src/pages/TimeLine/TimeLine.module.scss
  src/pages/TimeLine/TimeLine.tsx
  src/stores/registerStore.ts
Labels: feat, refactor

#57 Style/56 global color
  src/App.module.scss
  src/components/global/GlobalNavigationBar.module.scss
  src/components/login/LoginModal.module.scss
  src/components/profile_setting/ProfileInfoSetting.module.scss
  src/components/profile_setting/ProfileSettingModal.module.scss
  src/components/profile_setting/input/UserDataInput.module.scss
  src/components/timeLine/editorList/EditorList.module.scss
  src/components/timeLine/editorList/EditorProfileCard.module.scss
  src/components/timeLine/headerNavigation/HeaderNavigation.module.scss
  src/components/timeLine/keywordList/KeywordList.module.scss
  src/components/timeLine/leftBar/LeftBar.module.scss
  src/components/userProfile/EmptyUser.module.scss
  src/components/userProfile/UserInfoBar.module.scss
Labels: style

#60 Feat/58 userpage galleryview
  src/App.module.scss
  src/Router.tsx
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: feat

#62 GalleryView->MapEdit implemented
  src/components/userProfile/GetUser.module.scss
  src/components/userProfile/GetUser.tsx
Labels: feat
